# Generated by CODEFORGE v2.1 [NODAL] - 2026-06-08 10:44:39
# Program: GeneratedProgram

import sys
import os
import json
import logging
from datetime import datetime
from typing import Any, Dict, List, Optional, Tuple, Union

logging.basicConfig(level=logging.INFO, format='%(asctime)s [%(levelname)s] %(message)s')
logger = logging.getLogger(__name__)

# ─── Variables ───────────────────────────────────
NUCLEI_TARGET = None  # global

# ─── Function Definitions ────────────────────────
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Nuclei Template: CVE-2026-3055
Name: Citrix NetScaler SAML IDP - Memory Overread
Severity: critical
Description: NetScaler ADC and NetScaler Gateway contain an insufficient input validation vulnerability when configured as a SAML IDP, leading to memory overread, letting attackers potentially access sensitive memory, exploit requires configuration as SAML IDP
Auto-generated by NucleiForge
"""

import sys
import re
import json
import urllib.parse
import urllib.request
from typing import List, Dict, Any, Optional

class NucleiCheck_CVE_2026_3055:
    """Detection check generated from Nuclei template."""

    TEMPLATE_ID = "CVE-2026-3055"
    SEVERITY = "critical"
    NAME = "Citrix NetScaler SAML IDP - Memory Overread"

    def __init__(self, target: str, **kwargs):
        self.target = target.rstrip('/')
        self.protocol = "http"
        self.timeout = kwargs.get('timeout', 10)
        self.proxy = kwargs.get('proxy', None)
        self.follow_redirects = kwargs.get('follow_redirects', True)

    def run(self) -> Dict[str, Any]:
        """Execute the detection check."""
        result = {
            "template_id": self.TEMPLATE_ID,
            "name": self.NAME,
            "severity": self.SEVERITY,
            "target": self.target,
            "matched": False,
            "extracted": [],
            "error": None
        }

        try:
            url = self._build_url()
            response = self._send_request(url)

            if self._check_matchers(response):
                result["matched"] = True
                result["extracted"] = self._run_extractors(response)
                self._on_match(result)
            else:
                self._on_no_match(result)

        except Exception as e:
            result["error"] = str(e)
            self._on_error(e)

        return result

    def _build_url(self) -> str:
        """Construct target URL."""
        path = "/"
        # Replace Nuclei variables
        path = path.replace("{BaseURL}", self.target)
        path = path.replace("{BasePath}", "/")
        path = path.replace("{RootURL}", self.target)
        path = path.replace("{Hostname}", urllib.parse.urlparse(self.target).hostname or self.target)
        path = path.replace("{Port}", str(urllib.parse.urlparse(self.target).port or
                                          (443 if self.protocol == "https" else 80)))
        path = path.replace("{Path}", "/")
        path = path.replace("{Scheme}", self.protocol)

        # Random strings (simplified)
        import random, string
        path = re.sub(r'{randstr}', lambda m: ''.join(random.choices(string.ascii_lowercase, k=8)), path)
        path = re.sub(r'{rand_int}', lambda m: str(random.randint(1000, 9999)), path)

        return urllib.parse.urljoin(self.target, path)

    def _send_request(self, url: str) -> Dict[str, Any]:
        """Send HTTP request and return response dict."""
        import urllib.request
        import ssl

        req = urllib.request.Request(url, method="GET")

        # Headers
        headers = {}
        for k, v in headers.items():
            req.add_header(k, v)

        # SSL context
        ctx = ssl.create_default_context()
        ctx.check_hostname = False
        ctx.verify_mode = ssl.CERT_NONE

        # Proxy
        if self.proxy:
            req.set_proxy(self.proxy, 'http')

        # Body
        body = None
        if body:
            req.data = body.encode('utf-8')
            if 'Content-Type' not in headers:
                req.add_header('Content-Type', 'application/x-www-form-urlencoded')

        response = urllib.request.urlopen(req, timeout=self.timeout, context=ctx)

        return {
            "status_code": response.getcode(),
            "headers": dict(response.headers),
            "body": response.read().decode('utf-8', errors='replace'),
            "url": response.geturl()
        }

    def _check_matchers(self, response: Dict) -> bool:
        """Check response against matchers."""
        body = response.get("body", "")
        headers = str(response.get("headers", {}))
        status = response.get("status_code", 0)

        # TODO: Implement specific matchers from template
        # Current: basic string matching from detection summary
        detection = "[AND] DSL: regex('(?i)NSC_TASS=[A-Za-z0-9+/]+=*', set_cookie); status_code == 302"

        # Simple word matcher simulation
        matchers = ['(?i)NSC_TASS=[A-Za-z0-9+/]+=*']

        for matcher in matchers:
            if matcher.lower() in body.lower():
                return True
            if matcher.lower() in headers.lower():
                return True

        return False

    def _run_extractors(self, response: Dict) -> List[str]:
        """Run extractors on response."""
        extracted = []
        body = response.get("body", "")

        # Regex extractors (simplified)
        # TODO: Parse actual regex patterns from template

        return extracted

    def _on_match(self, result: Dict):
        """Handle match event."""
        print(f"[MATCH] {result['name']} on {result['target']}")
        print(f"        Severity: {result['severity']}")

    def _on_no_match(self, result: Dict):
        """Handle no-match event."""
        print(f"[NO MATCH] {result['name']} on {result['target']}")

    def _on_error(self, error: Exception):
        """Handle error event."""
        print(f"[ERROR] {error}", file=sys.stderr)


def main():
    """CLI entry point."""
    import argparse
    parser = argparse.ArgumentParser(description="Citrix NetScaler SAML IDP - Memory Overread")
    parser.add_argument("target", help="Target URL/hostname")
    parser.add_argument("--proxy", help="Proxy URL")
    parser.add_argument("--timeout", type=int, default=10)
    args = parser.parse_args()

    checker = NucleiCheck_CVE_2026_3055(
        target=args.target,
        proxy=args.proxy,
        timeout=args.timeout
    )
    result = checker.run()

    print(json.dumps(result, indent=2, ensure_ascii=False))
    sys.exit(0 if result["matched"] else 1)


if __name__ == "__main__":
    main()

#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Nuclei Template: CVE-2026-41940
Name: cPanel & WHM - Authentication Bypass via Session-File CRLF Injection
Severity: critical
Description: cPanel and WHM versions prior to 11.110.0.97, 11.118.0.63, 11.126.0.54, 11.132.0.29, 11.134.0.20, and 11.136.0.5 contain an authentication bypass vulnerability in the login flow that allows unauthenticated remote attackers to gain unauthorized access to the control panel.
Auto-generated by NucleiForge
"""

import sys
import re
import json
import urllib.parse
import urllib.request
from typing import List, Dict, Any, Optional

class NucleiCheck_CVE_2026_41940:
    """Detection check generated from Nuclei template."""

    TEMPLATE_ID = "CVE-2026-41940"
    SEVERITY = "critical"
    NAME = "cPanel & WHM - Authentication Bypass via Session-File CRLF Injection"

    def __init__(self, target: str, **kwargs):
        self.target = target.rstrip('/')
        self.protocol = "http"
        self.timeout = kwargs.get('timeout', 10)
        self.proxy = kwargs.get('proxy', None)
        self.follow_redirects = kwargs.get('follow_redirects', True)

    def run(self) -> Dict[str, Any]:
        """Execute the detection check."""
        result = {
            "template_id": self.TEMPLATE_ID,
            "name": self.NAME,
            "severity": self.SEVERITY,
            "target": self.target,
            "matched": False,
            "extracted": [],
            "error": None
        }

        try:
            url = self._build_url()
            response = self._send_request(url)

            if self._check_matchers(response):
                result["matched"] = True
                result["extracted"] = self._run_extractors(response)
                self._on_match(result)
            else:
                self._on_no_match(result)

        except Exception as e:
            result["error"] = str(e)
            self._on_error(e)

        return result

    def _build_url(self) -> str:
        """Construct target URL."""
        path = "/"
        # Replace Nuclei variables
        path = path.replace("{BaseURL}", self.target)
        path = path.replace("{BasePath}", "/")
        path = path.replace("{RootURL}", self.target)
        path = path.replace("{Hostname}", urllib.parse.urlparse(self.target).hostname or self.target)
        path = path.replace("{Port}", str(urllib.parse.urlparse(self.target).port or
                                          (443 if self.protocol == "https" else 80)))
        path = path.replace("{Path}", "/")
        path = path.replace("{Scheme}", self.protocol)

        # Random strings (simplified)
        import random, string
        path = re.sub(r'{randstr}', lambda m: ''.join(random.choices(string.ascii_lowercase, k=8)), path)
        path = re.sub(r'{rand_int}', lambda m: str(random.randint(1000, 9999)), path)

        return urllib.parse.urljoin(self.target, path)

    def _send_request(self, url: str) -> Dict[str, Any]:
        """Send HTTP request and return response dict."""
        import urllib.request
        import ssl

        req = urllib.request.Request(url, method="GET")

        # Headers
        headers = {}
        for k, v in headers.items():
            req.add_header(k, v)

        # SSL context
        ctx = ssl.create_default_context()
        ctx.check_hostname = False
        ctx.verify_mode = ssl.CERT_NONE

        # Proxy
        if self.proxy:
            req.set_proxy(self.proxy, 'http')

        # Body
        body = None
        if body:
            req.data = body.encode('utf-8')
            if 'Content-Type' not in headers:
                req.add_header('Content-Type', 'application/x-www-form-urlencoded')

        response = urllib.request.urlopen(req, timeout=self.timeout, context=ctx)

        return {
            "status_code": response.getcode(),
            "headers": dict(response.headers),
            "body": response.read().decode('utf-8', errors='replace'),
            "url": response.geturl()
        }

    def _check_matchers(self, response: Dict) -> bool:
        """Check response against matchers."""
        body = response.get("body", "")
        headers = str(response.get("headers", {}))
        status = response.get("status_code", 0)

        # TODO: Implement specific matchers from template
        # Current: basic string matching from detection summary
        detection = '[OR] DSL: status_code == 401; contains(header, "whostmgrrelogin") / [OR] DSL: status_code == 307; contains(location, "cpsess") / [OR] DSL: status_code == 401'

        # Simple word matcher simulation
        matchers = ['test']

        for matcher in matchers:
            if matcher.lower() in body.lower():
                return True
            if matcher.lower() in headers.lower():
                return True

        return False

    def _run_extractors(self, response: Dict) -> List[str]:
        """Run extractors on response."""
        extracted = []
        body = response.get("body", "")

        # Regex extractors (simplified)
        # TODO: Parse actual regex patterns from template

        return extracted

    def _on_match(self, result: Dict):
        """Handle match event."""
        print(f"[MATCH] {result['name']} on {result['target']}")
        print(f"        Severity: {result['severity']}")

    def _on_no_match(self, result: Dict):
        """Handle no-match event."""
        print(f"[NO MATCH] {result['name']} on {result['target']}")

    def _on_error(self, error: Exception):
        """Handle error event."""
        print(f"[ERROR] {error}", file=sys.stderr)


def main():
    """CLI entry point."""
    import argparse
    parser = argparse.ArgumentParser(description="cPanel & WHM - Authentication Bypass via Session-File CRLF Injection")
    parser.add_argument("target", help="Target URL/hostname")
    parser.add_argument("--proxy", help="Proxy URL")
    parser.add_argument("--timeout", type=int, default=10)
    args = parser.parse_args()

    checker = NucleiCheck_CVE_2026_41940(
        target=args.target,
        proxy=args.proxy,
        timeout=args.timeout
    )
    result = checker.run()

    print(json.dumps(result, indent=2, ensure_ascii=False))
    sys.exit(0 if result["matched"] else 1)


if __name__ == "__main__":
    main()


# ─── Main Execution ──────────────────────────────
def main() -> None:
    logger.info("Starting GeneratedProgram")

    Citrix NetScaler SAML IDP - Memory Overread(NUCLEI_TARGET)
    cPanel & WHM - Authentication Bypass via Session-File CRLF Injection(NUCLEI_TARGET)
    logger.info("GeneratedProgram completed.")

if __name__ == "__main__":
    main()